spring:
  application:
    name: rogator
  devtools:
    add-properties: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: rogator
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      connection-init-sql: SET search_path TO rogator
      max-lifetime: 480000            #8m
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000            #5m
      keepalive-time: 120000          #2m
      connection-timeout: 30000       #30s
  jpa:
    show-sql: true
    defer-datasource-initialization: false
    properties:
      hibernate:
          format_sql: true
          use_sql_comments: true
          default_schema: rogator
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: issuer
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 10MB
      enabled: true
      location: ${java.io.tmpdir}
  profiles:
    active: local
  mail:
    host: ${mail-config.host}
    port: ${mail-config.port}
    username: ${mail-config.user.email}
    password: ${mail-config.user.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /rogator

app:
  storage:
    root: /data/uploads
    attachmentsFolderName: applications-attachments
  application:
    creation:
      durability: 3600 # 6 hours

#Payment details
payment:
  paypal:
    mode: <mode>
    client-id: <clientId>
    client-secret: <clientSecret>
    currency-code: <currencyCode>

#Jobs
cron:
  change-application-status: 0 0 * * * *

#Email
mail-config:
  host: <host>
  port: 001
  user:
    email: <email>
    username: <username>
    password: <password>
