spring:
  application:
    name: rogator
  devtools:
    add-properties: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/kumpo/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health, info
